sudo: required

language: csharp

mono: none
dotnet: 2.1.505
solution: Rave.sln
script:
 - dotnet restore
 - dotnet test

jobs:
  include:
    - script: echo "Running unit tests"
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
      on:
        tags: true
